Introduce budget, reimbursements for expenses
67P/kredits-web pull request #195
Opened 2020-10-01 10:56 UTC by skddc

This is a big one. It isn't linked from the dashboard yet, but you can browse to `/budget` and propose reimbursements from there.

Requires https://github.com/67P/kredits-contracts/pull/198

## To do

* [ ] Fix bug in contract wrapper, which claims expense amounts are missing, when they're not
* [ ] Test locally on various machines
* [ ] Deploy reimbursement contract/s
* [ ] Test in production

2020-10-30 14:30 UTC, raucao commented
I just finished the functionality of the PR, so there are just the linter errors left. You can test it on your machines now.

There's one known issue, which won't be much of a problem in a production: a race condition, when your tx confirms within the loading of the reimbursement list after pressing the submit button on the reimbursement form. I'm not sure how to handle that, and it doesn't break anything in the unlikely case that you see this  in production. Just reload the page and all is good, due to the caching and syncing logic.

2020-10-31 12:43 UTC, raucao commented
All done and ready to merge from my point of view.

2020-11-17 11:13 UTC, galfert requested changes
Wow, that was a lot of changes :)

Left a few comments.

So far I wasn't able to test it manually, because of problems running the contracts (see XMPP).

2020-11-17 11:47 UTC, raucao commented on app/components/add-reimbursement/component.js
> +      expenses: JSON.parse(JSON.stringify((this.expenses)))
It's to get rid of the EmberObject properties and only retain the pure expense data in the object handed to the wrapper.

2020-11-17 11:49 UTC, raucao commented on app/services/exchange-rates.js
> +  } catch(e) {
If it is not OK, then this already just gracefully fails by not automatically converting numbers.

2020-11-17 12:37 UTC, raucao commented on app/services/community-funds.js
> +      .catch(err => {
This gracefully fails by catching the exception in `processBalances` I think.

2020-11-17 12:38 UTC, raucao commented on app/services/kredits.js
> +    return Promise.resolve();
Didn't know that. Not sure I like it being implicit here...

2020-11-17 12:39 UTC, raucao commented on app/components/add-expense-item/component.js
> +    return true;
I guess it's just a leftover from before the proper form validation.

2021-06-02 12:27 UTC, raucao commented
@galfert Did you see my replies? I just merged the corresponding contracts PR, so it'd be great if we can merge this one as well now.

2021-06-03 10:19 UTC, galfert approved these changes
LGTM

2021-06-03 14:23 UTC, merged